---
- name: include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - vars

# - name: debian vars
#  include_vars: Debian.yml
#  when: ansible_os_family == 'Debian'
#
# - name: redhat vars
#  include_vars: RedHat.yml
#  when: ansible_os_family == 'RedHat'

- name: download firefox package
  get_url:
    url: "{{ firefox_url }}"
    dest: /tmp/firefox-{{ firefox_version }}.tar.bz2
    checksum: "{{ firefox_checksum }}"

- block:
    - name: remove the firefox package
      package:
        name: firefox
        state: absent

    - name: install dependencies
      package:
        name: "{{ item }}"
      with_items: "{{ firefox_dependencies }}"

    - name: create install directory
      file:
        path: "{{ firefox_home }}"
        state: directory
        mode: 0755

    - name: unarchive package
      unarchive:
        src: "{{ firefox_download }}"
        dest: "{{ firefox_home }}"
        remote_src: true
        creates: "{{ firefox_bin }}"

    - name: symlink package
      file:
        src: "{{ firefox_bin }}"
        dest: /usr/bin/firefox
        state: link
  become: true

- name: create desktop icon
  template:
    src: firefox.desktop.j2
    dest: /usr/share/applications/firefox.desktop
    owner: root
    group: root
    mode: 0644
  when: firefox_desktop_icon
