---
- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Include distribution specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - vars

- name: Install via tarball
  ansible.builtin.import_tasks:
    file: tarball.yml
  when:
    - ansible_facts.os_family != "Debian"

- name: Install via deb
  ansible.builtin.import_tasks:
    file: deb.yml
  when:
    - ansible_facts.os_family == "Debian"
